<?php
/**
 * @file
 * Module file for hello_world.
 */


/**
 * Implements hook_block_init().
 *
 * This hook initializes stuff for the module.
 */

function hello_world_init() {

  if (arg(0) == 'node' && is_numeric(arg(1))) {

    $node = node_load(array('nid' => arg(1)));

    ($node->type == 'article') &&
      drupal_add_css(drupal_get_path('module', 'hello_world') .
      '/hello_world.css');

  }

}


/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */

function hello_world_block_info() {

  $blocks['hello_world_sidebar'] = array(

    'info' => t('Hello World! Sidebar'),
    'status' => TRUE,
    'region' => 'sidebar_second',
    'weight' => -59,
    'visibility' => BLOCK_VISIBILITY_PHP,

    'pages' => '<?php

  if (arg(0) == \'node\' && is_numeric(arg(1))) {

    $node = node_load(array(\'nid\' => arg(1)));
    if ($node->type == \'article\') return TRUE;

  }

  return FALSE;
?>',
  );

  return $blocks;

}


/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */

function hello_world_block_view($delta = '') {

  switch ($delta) {

    case 'hello_world_sidebar':

      $block['subject'] = ''; // t('Hello World!');
      $block['content'] = 'Hello World!';
      break;

  }

  return $block;

}


/**
 * Implements hook_node_view_alter(&$build).
 *
 * This hook alters the content of the node.
 */

function hello_world_node_view_alter(&$build) {

  if (arg(0) == 'node' && is_numeric(arg(1))) {

    $node = node_load(array('nid' => arg(1)));

    if (($node->type == 'article') && ($build['#view_mode'] == 'full')) {

      $build['hello_world'] = array(

        '#type' => 'markup',
        '#markup' => 'Content starts here!',
        '#prefix' => '<div class="hello-world-ital">',
        '#suffix' => '</div>',
        '#weight' => -59,

      );

    } // article and full view mode?

  } // node/nid?

}
