; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.36"
projects[drupal][type] = "core"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[auto_nodetitle][version] = "1.0"

projects[block_class][version] = "2.1"

projects[ctools][version] = "1.7"

projects[ckeditor][version] = "1.16"

projects[codefilter][version] = "1.1"

projects[devel][version] = "1.5"

projects[draggableviews][version] = "2.1"

projects[entity][version] = "1.6"

projects[media][version] = "1.5"

projects[geshifilter][version] = "1.2"

projects[panels][version] = "3.5"

projects[jcarousel][version] = "2.7"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[markdown][version] = "1.2"

projects[mobile_theme][version] = "1.2"

projects[oauth][version] = "3.2"

projects[pathauto][version] = "1.2"

projects[rotating_banner][version] = "2.x-dev"

projects[token][version] = "1.6"

projects[twitter][version] = "5.8"

projects[typogrify][version] = "1.0-rc10"

projects[video_embed_field][version] = "2.0-beta8"

projects[views][version] = "3.10"

; Themes
projects[mobile][version] = "2.0"
projects[mobile][type] = "theme"

; Modules


; Themes
projects[gdg][download][type] = ""
projects[gdg][download][url] = ""
projects[gdg][type] = "theme"

; Libraries
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[geshi][download][type] = ""
libraries[geshi][download][url] = ""
libraries[geshi][directory_name] = "geshi"
libraries[geshi][type] = "library"


